#!/usr/bin/env bash
# script that will display information about subdomains.

if [ $# -le 1 ]; then
    dig "www.""$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain www is a " $4 " record and points to " $5 }' | tail -n 1
    dig "lb-01.""$1"  | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5 }' | tail -n 1
    dig "web-01.""$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5 }' | tail -n 1
    dig "web-02.""$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5 }' | tail -n 1
else
    echo -n "The subdomain $2"
    dig "$2"".""$1" | grep -A1 'ANSWER SECTION:' | awk '{print " is a " $4 " record and points to " $5 }' | tail -n 1
fi

