#!/usr/bin/env bash
# script that transfers a file from our client to a server
if [[ $# < 3 ]]
then
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
else
	echo "$4" "$1" "$3@$2:~"
fi
