#!/usr/bin/env bash
# script that redirect

apt-get update
apt-get -y install nginx
echo Holberton School > /var/www/html/index.html
new_string="https://www.youtube.com/watch?v=QH2-TGUlwu4"
file="/etc/nginx/sites-available/default"

sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_string permanent;" $file


service nginx restart
