#!/usr/bin/env bash
# iInstall and configure HAproxy on your lb-01 server.
apt-get update
apt-get install -y haproxy
dir="/etc/haproxy/haproxy.cfg"

{
echo -e "\tfrontend first_front"
echo -e "\t\tbind *:80"
echo -e "\t\tstats uri /haproxy?stats"
echo -e "\t\tdefault_backend first_back"

echo -e "\n\tbackend first_back"
echo -e "\t\tbalance roundrobin"
echo -e "\t\tserver 2239-web-01 35.237.246.228:80 check"
echo -e "\t\tserver 2239-web-02 35.190.168.95:80 check"
} >> $dir

service haproxy start
