#!/usr/bin/env bash
# script that pings an IP address passed as an argument.

# Requirements:

# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times

if [ "$1" ]
then
	echo "Total number of arguments: $#"
	echo "Argument 1: $0"
	echo "Argument 1: $1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
