#!/usr/bin/env bash
# Write a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

f="$(ls)"

for i in $f
do
	echo "$i" | cut -d "-" -f 2
done