#!/usr/bin/env bash
# script that configures the containe, running as nginx user, listening on all active IPs on port 8080
chmod 777 /etc/nginx/nginx.conf
sed -i -e 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i -e 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo systemctl restart nginx
